;>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
; 1DT301, Computer Technology I
; Date: 2018-09-14
; Author:
; Amata Anantaprayoon (aa224iu)
; Adell Tatrous (at222ux)
;
; Lab number: 1
; Title: How to use the PORTs. Digital input/output. Subroutine call.
;
; Hardware: STK600, CPU ATmega2560
;
; Function: Creats a Ring Counter
; Input ports: N/A
;
; Output ports: PORTB.
;
; Subroutines: 0.5 sec dealy in between each count
; Included files: m2560def.inc
;
; Other information: ; Generated by delay loop calculator
;                      at http://www.bretmulvey.com/avrdelay.html
;
; Changes in program: 2018-09-14: Implementation
;                     2018-09-16: Edit comments
;
;<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<


.include "m2560def.inc"
.def dataDir = r16
.def ledOn = r17

; Initialize SP, Stack Pointer
ldi r20, HIGH(RAMEND)			; R20 = high part of RAMEND address
out SPH,R20						; SPH = high part of RAMEND address
ldi R20, low(RAMEND) 			; R20 = low part of RAMEND address
out SPL,R20						; SPL= low part of RAMEND address

;set port B as output
ldi dataDir, 0xFF
out DDRB, dataDir

start:

;Lights LED0
ldi ledOn, 0b1111_1110
out PORTB, ledOn

loop:

; Delay 500 000 cycles
; 500ms at 1 MHz

    ldi  r18, 3
    ldi  r19, 138
    ldi  r20, 86
L1: dec  r20
    brne L1
    dec  r19
    brne L1
    dec  r18
    brne L1
    rjmp PC+1

lsl ledOn 		        ; shift last bit to the left 
inc ledOn		        ; add 1 to the current bit 
out PORTB, ledOn

cpi ledOn, 0xFF         ; compare ledOn with 0xFF
breq start 		        ; IF ledOn = 0xFF jump to start

rjmp loop
